version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3342:3342
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Paris
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_LOG=none
      - TZ=Europe/Paris
    depends_on:
      - db
    logging:
      driver: "none"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - FAST_REFRESH=true # React's hot reload
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=3342
    env_file:
      - .env
    depends_on:
      - db
